### ISSUE TITLE
Delay for the first left-click attack.

### ISSUE THREAD

**Issue by thivod** [TwistedScorpio/OTHire#197] opened 2018-05-29 04:46 UTC
At CipfSoft 7.7 tibia, there was a little delay when the player sets the left click attack on a monster or another player, before the attack itself came out.

**Comment by peonso** [comment] 2018-05-29 20:12
I got mixed results from testing, some attacks got delayed, but some attacks go as fast as I click, as if it happen someway like this https://github.com/TwistedScorpio/OTHire/issues/103#issuecomment-337101166. As if there are times where it check for attack and if it matches with the left-click it happens instantly, else it waits for the trigger. The way OTServ and Tibia Server handle those sort of stuff is totally different and I'm guessing here, but it would probably be a pain in the ass to try to match things.

**Comment by Ochmar** [comment] 2018-10-18 23:01
Are there any solution nearby? It's very frustrating when using spears, for example. (Each onhand drag makes it delay).

**Comment by peonso** [comment] 2018-10-19 22:44
@Ochmar this is an unrelated issue, test please if changing WEAPON_NONE for WEAPON_DIST in this line fix your problem. https://github.com/TwistedScorpio/OTHire/blob/76717e719c4469bdfe47bea35e966fa78210a5c9/source/player.cpp#L2950

But was this present in 7.72? I'm not sure, can you test in a real server?

**Comment by thivod** [comment] 2018-10-20 17:53
@Ochmar You could easily test this issue and others at http://experimental.realots.org.
I tested it a bit and ur right, there is no delay when u throw a spear and drag to ur hand the same spear you've just thrown.

**Comment by thivod** [comment] 2018-10-20 17:56
@peonso do u think changing  WEAPON_NONE for WEAPON_DIST will fix this?

Another thing I just realised is that if u got a xbow on, none of the hits u receive makes the shielding animation (they wont puff), i think there is already a issue openned for that, isnt there?

**Comment by Ochmar** [comment] 2018-10-20 18:05
@peonso Yes, there should be no delay.
And yes, changing it to WEAPON_DIST works like a charm. Thank you so much.

@thivod Thanks for this link, will definitely take a look.

**Comment by Wirless** [comment] 2018-11-12 22:18
this should be configuable in config lua exAction exhaust or action exhaust just obfuscate ammo from it

**Comment by peonso** [comment] 2020-12-18 14:15
This one is considered duplicate of #103

**Closed by peonso** 2020-12-18 14:15 UTC
Labels: enhancement
