### ISSUE TITLE
frag time decrease

### ISSUE THREAD

**Issue by Stoudemire** [TwistedScorpio/OTHire#120] opened 2016-12-05 14:19 UTC
where I can config frag time decrease?
@peonso @diegorodriguesvieira

**Comment by Stoudemire** [comment] 2016-12-07 22:28
frags decrease time bug, ban x kills bug, all system is buged

**Comment by TwistedScorpion** [comment] 2016-12-12 03:55
Maybe you should stop asking for bugs to be fixed and start doing fixes by your own.
I'm not being rude but you should learn some programming code... Since every bug you have encountered is being fixed by another person.

If OTHire does not satisfies you, then you should move to TFS or something else and stop asking for help.
If you can't handle some of these bugs then you will hardly ever have a successful OTserver.

Good luck!

**Comment by peonso** [comment] 2016-12-13 03:03
That's total bullshit. This section is meant exactly for purpose of reporting issues. By doing so he is helping the entire community.

**Comment by diegorodriguesvieira** [comment] 2016-12-13 10:03
Total bullshit!

**Comment by peonso** [comment] 2017-02-26 02:33
It seems to be working as intended, if there is any issue please give a complete report of what you did, what happened and what was expected.

**Closed by peonso** 2017-02-26 02:33 UTC
Labels: bug
